{% set name = "rapidfuzz_capi" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rapidfuzz_capi-{{ version }}.tar.gz
  sha256: b3af179874b28364ba1b7850e37d0d353de9cf5b844e3569c023b74da3a9c68e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - rapidfuzz_capi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/maxbachmann/rapidfuzz_capi
  summary: C-API of RapidFuzz, which can be used to extend RapidFuzz from separate packages
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/maxbachmann/rapidfuzz_capi

extra:
  recipe-maintainers:
    - maxbachmann
